#!/usr/bin/env sh
while read file
do
	case "$1" in
		"e") devour display "$file" & ;;
		"w") setbg "$file" & ;;
		"c")
			[ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/directories | awk '{print $2}' | dmenu -l 20 -i -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
			[ -z "$destdir" ] && exit
			[ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
			cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." &
			;;
		"m")
			[ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/directories | awk '{print $2}' | dmenu -l 20 -i -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
			[ -z "$destdir" ] && exit
			[ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
			mv "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file moved to $destdir." &
			;;
		"r")
			convert -rotate 90 "$file" "$file" ;;
		"R")
			convert -rotate -90 "$file" "$file" ;;
		"f")
			convert -flop "$file" "$file" ;;
		"y")
			echo -n "$file" | xclip -selection clipboard &&
			notify-send "$file copied to clipboard" & ;;
		"Y")
			[ $(mimetype -Mb "$file") = "image/png" ] && \ 
			xclip -sel c -t "image/png" "$file" || \ 
			convert "$file" png:- | xclip -select  clipboard -t "image/png" & ;;
		"d")
			[ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
		"g")	ifinstalled gimp && gimp "$file" & ;;
	esac
done
