#!/bin/sh

MIMETYPE="$( file --dereference --brief --mime-type -- "$1" )"

case $MIMETYPE in
	*gzip) tar tzf "$1" ;;
	*txz) xz --list "$1" ;;
	*tar) tar tf "$1" ;;
	*/zip|*java-archive) unzip -l "$1" ;;
	*rar) unrar l "$1" ;;
	*7z) 7z l "$1" ;;
	*)
		[ "$( stat --printf='%s' -- "$1" )" -gt "262143" ] && exit 2
		less "$1" ;;
esac
exit 0

