gui:
  scrollHeight: 10
  showRandomTip: false
  showCommandLog: false
  showFileTree: true
  theme:
    selectedLineBgColor:
      - reverse

customCommands:
  - key: 'C'
    command: 'cpr {{.SelectedLocalBranch.Name}}'
    description: 'Create PR'
    context: 'localBranches'
  - key: 'F'
    command: 'alacritty -e lf {{.SelectedFile.Name}}'
    description: 'Open file location'
    context: 'files'

os:
  editCommand: 'nvim +{{line}} {{filename}}'
  openCommand: 'code {{filename}}'
