gui:
  scrollHeight: 10
  showRandomTip: false
  showBottomLine: false
  showCommandLog: false
  showFileTree: true
  expandFocusedSidePanel: true
  theme:
    selectedLineBgColor:
      - reverse

customCommands:
  - key: 'C'
    command: 'cpr'
    description: 'Create PR'
    context: 'localBranches'
    subprocess: true
  - key: 'G'
    command: 'open-remote -b "{{.SelectedLocalBranch.Name}}" -m {{index .PromptResponses 0}}'
    description: 'Open remote branch'
    context: 'localBranches'
    prompts:
      - type: 'menu'
        title: 'What to open?'
        options:
          - value: 'tree'
          - value: 'pr'
  - key: 'F'
    command: 'alacritty -e lf {{.SelectedFile.Name}}'
    description: 'Open file location'
    context: 'files'
  - key: '<c-y>'
    description: 'Create Patch'
    context: 'files'
    command: 'send-text {{index .PromptResponses 0}} {{index .PromptResponses 1}} "$(git diff --cached)"'
    prompts:
      - type: 'menu'
        title: 'Where to save?'
        options:
          - value: 'drop'
          - value: 'file'
      - type: 'input'
        title: 'File Name:'

os:
  edit: '[[ "$(realpath {{filename}})" == *"/git/"* ]] && code -g {{filename}} || nvim {{filename}}'
  editAtLine: '[[ "$(realpath {{filename}})" == *"/git/"* ]] && code -g {{filename}}:{{line}} || nvim +{{line}} {{filename}}'

promptToReturnFromSubprocess: false
