gui:
  scrollHeight: 10
  showRandomTip: false
  showCommandLog: false
  showFileTree: true
  theme:
    selectedLineBgColor:
      - reverse

customCommands:
  - key: 'C'
    command: 'cpr {{.SelectedLocalBranch.Name}}'
    context: 'localBranches'

os:
  editCommand: 'nvim +{{line}} {{filename}}'
  openCommand: 'code {{filename}}'
