---
If:
  PathMatch: .*/config\.h
CompileFlags:
  Add:
    - -x
    - c
    - -std=gnu11
    - -include
    - dwm.c

---
If:
  PathMatch: .*/(file-handler|bluetooth|music)\.c
CompileFlags:
  Add:
    - -ldbus-1
    - -I/usr/include/dbus-1.0
    - -I/usr/lib/dbus-1.0/include

---
If:
  PathMatch: .*/(image-tag-handler|roku-remote)\.c
CompileFlags:
  Add:
    - -I/usr/include/glib-2.0
    - -I/usr/lib/glib-2.0/include
    - -I/usr/include/gdk-pixbuf-2.0
