#!/bin/sh

# $1: path to image file
# $2: image width
# $3: image height

exec 2>/dev/null

filename=$(basename -- "$1")
filesize=$(du -Hh -- "$1" | cut -f 1)
geometry="${2}x${3}"

echo "${filesize} ${geometry} ${filename}"
