#!/usr/bin/env sh
while read file
do
	case "$1" in
		"e") devour display "$file" & ;;
		"r") convert -rotate 90 "$file" "$file" ;;
		"R") convert -rotate -90 "$file" "$file" ;;
		"f") convert -flop "$file" "$file" ;;
		"y")
			echo -n "$file" | xclip -selection clipboard &&
			notify-send "$file copied to clipboard" & ;;
		"Y")
			[ $(mimetype -Mb "$file") = "image/png" ] && \ 
			xclip -sel c -t "image/png" "$file" || \ 
			convert "$file" png:- | xclip -select  clipboard -t "image/png" & ;;
		"d")
			[ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
		"g") ifinstalled gimp && gimp "$file" & ;;
	esac
done
