#!/usr/bin/env sh

. utils

rename() {
	name="$(basename "$file")"
	dir="$(dirname "$file")"
	newName="$(prompt "Rename:" <<< "$name" || exit 0)"
	newName="$(getfilename "$newName")"
	mv "$file" "$newName"
}

copyImage() {
	if [ $(mimetype -Mb "$file") = "image/png" ]; then
		xclip -sel c -t "image/png" "$file" >/dev/null 2>&1 &
	else
		convert "$file" png:- | xclip -sel c -t "image/png" &
	fi
}

while read file; do
	case "$1" in
		"r") rename ;;
		"e") devour /opt/Gimp.AppImage "$file" & ;;
		"bracketright") convert -rotate 90 "$file" "$file" ;;
		"bracketleft") convert -rotate -90 "$file" "$file" ;;
		"f") convert -flop "$file" "$file" ;;
		"y") echo -n "$file" | xclip -sel c && notify "$file copied " & ;;
		"Y") copyImage ;;
		"d") [ $(prompt "Delete $file?" <<< $'No\nYes') = "Yes" ] &&
			rm "$file" && notify "$file deleted." ;;
	esac
done
