#!/usr/bin/env sh

echo $1 > ~/log

while read file
do
	case "$1" in
		"r") name="$(basename "$file")"
			dir="$(dirname "$file")"
			newName="$(dmenu -i -p "Rename:" <<< "$name" || exit 0)"
			if [ -e "$newName" ]; then
				i=1
				while [ -e "$dir/$newName-$i" ]; do
					i=$((i+1))
				done
				newName="$dir/$newName$i"
			fi
			mv "$file" "$newName"
			;;
		"e") devour display "$file" & ;;
		"bracketright") convert -rotate 90 "$file" "$file" ;;
		"bracketleft") convert -rotate -90 "$file" "$file" ;;
		"f") convert -flop "$file" "$file" ;;
		"y")
			echo -n "$file" | xclip -selection clipboard &&
			notify-send "$file copied to clipboard" & ;;
		"Y")
			[ $(mimetype -Mb "$file") = "image/png" ] && \ 
			xclip -sel c -t "image/png" "$file" || \ 
			convert "$file" png:- | xclip -select  clipboard -t "image/png" & ;;
		"d")
			[ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
		"g") ifinstalled gimp && gimp "$file" & ;;
	esac
done
