#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner" \

# Colorize commands when possible.
alias \
	ls="ls -N --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	i="nsxiv -p" \
	p="sudo pacman" \
	c="comms" \
	lf="lfcd" \
	lg="lazygit"

# Run white script for all staged files in current git repository
wsg() {
	git status --porcelain | grep '^\w.'| awk '{print $2}' | while read -r line; do
		white "`git rev-parse --show-toplevel`/$line";
	done
}

